FROM python:3.12 as base

WORKDIR /app
ENV PR_AGENT_PRO=true
ENV PR_AGENT_LICENSE=pro
ADD pyproject.toml .
ADD requirements.txt .
RUN pip install --no-cache-dir . && rm pyproject.toml requirements.txt
ENV PYTHONPATH=/app
ADD docs docs
ADD pr_agent pr_agent
ADD github_action/entrypoint.sh /
RUN chmod +x /entrypoint.sh
COPY .pr_agent.toml /root/.pr_agent_global_settings.toml
ENTRYPOINT ["/entrypoint.sh"]
